# student's biography
print("STUDENT'S BIOGRAPHY")
students_list = []
n = int(input("Enter the student list: "))
for i in range(0, n):
    name = str(input("enter students name: "))
    students_list.append(name)
    registration_number = str(input("REGISTRATION NUMBER:"))
    students_list.append(registration_number)
    age = int(input("Age: "))
    students_list.append(age)
    nationality = str(input("enter the student's nationality: "))
    students_list.append(nationality)
    phone_number = int(input("Enter the student's phone number: "))
    students_list.append(phone_number)
    batch_year = int(input("enter the student's year of study: "))
    students_list.append(batch_year)
    course = str(input("Enter the student's course of study: "))
    students_list.append(course)
    program = str(input("Enter student's course of study: "))
    students_list.append(program)
    graduation_year = int(input("enter the expected year of graduation: "))
    students_list.append(graduation_year)
print("student Name:{name}")
print("Registration Number: {registration_number}")
print("Age: {age}")
print("Nationality:{nationality}")
print("Phone Number: {phone_number}")
print("Year of study: {batch_year}")
print("Course of study: {course}")
print("Program admitted: {program}")
print("Expected Graduation Year: {graduation_year}")
print("WELCOME TO THE SOURCE OF INNOVATIONS AND CREATIVITY")
